{% set name = "procrunner" %}
{% set version = "0.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c1712fd10a626440ac3925e7458cc39f213f5a551f94dc90894ac34233c04d0

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - pytest-runner
    - pip
    - six
  run:
    - python
    - six

test:
  imports:
    - procrunner

about:
  home: https://github.com/DiamondLightSource/python-procrunner
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Versatile utility function to run external processes
  description: Versatile utility function to run external processes
  dev_url: https://github.com/DiamondLightSource/python-procrunner
  doc_url: https://procrunner.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - bkpoon
